apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: assisted-opensearch
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      prometheus: app-sre
    name: servicemonitor-assisted-opensearch-${NAMESPACE}
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: "http"
      scheme: http
      metricRelabelings:
      - sourceLabels: [cluster]
        regex:  '\d+:(.*)'
        replacement: '$1'
        targetLabel: cluster
    namespaceSelector:
      matchNames:
      - ${NAMESPACE}
    selector:
      matchLabels:
        app: prometheus-opensearch-exporter
parameters:
- name: NAMESPACE
  required: true
